[formatting]
align_entries = false
align_comments = true
array_auto_collapse = true
array_auto_expand = true
column_width = 100
indent_string = "    "
reorder_keys = false
trailing_newline = true

[[rule]]
include = ["**/Cargo.toml"]

[rule.formatting]
reorder_keys = false
