//! Phase 3.5 / step 19 canonicalization test vectors.
//!
//! Each vector is `(description, ReceiptBody constructor, expected
//! canonical bytes hex, expected BLAKE3 hex)`. These commit the
//! v2 (RFC 8785 JCS) wire format to disk: any change to
//! `canonical.rs` that alters byte-level output for the same
//! logical receipt will fail at least one of these assertions.
//!
//! The same logical bodies are also exposed as a JSON fixture
//! for cross-language verifier conformance — see
//! `tests/vectors/canonical-v2.json` (auto-generated by the
//! `dump_canonical_vectors_to_file` test below).
//!
//! Adding a vector:
//! 1. Build the `ReceiptBody` in [`vector_bodies`].
//! 2. Run `cargo test -p uniclaw-receipt --test vectors -- --nocapture
//!    print_vectors` to print the (`canonical_hex`, `blake3_hex`) for
//!    the new vector.
//! 3. Paste those values into [`expected_outputs`] alongside the
//!    body's index.
//! 4. Re-run; the snapshot test passes.

use uniclaw_receipt::{
    Action, Decision, Digest, MerkleLeaf, ProvenanceEdge, RECEIPT_FORMAT_VERSION, ReceiptBody,
    RuleRef,
};

fn vector_bodies() -> Vec<(&'static str, ReceiptBody)> {
    vec![
        (
            "minimal-allowed",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:00Z".into(),
                action: Action {
                    kind: "http.fetch".into(),
                    target: "https://example.com/".into(),
                    input_hash: Digest([0u8; 32]),
                },
                decision: Decision::Allowed,
                constitution_rules: vec![],
                provenance: vec![],
                redactor_stack_hash: None,
                key_id: None,
                merkle_leaf: MerkleLeaf {
                    sequence: 0,
                    leaf_hash: Digest([1u8; 32]),
                    prev_hash: Digest([0u8; 32]),
                },
            },
        ),
        (
            "denied-with-rule",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:01Z".into(),
                action: Action {
                    kind: "shell.exec".into(),
                    target: "rm -rf /".into(),
                    input_hash: Digest([2u8; 32]),
                },
                decision: Decision::Denied,
                constitution_rules: vec![RuleRef {
                    id: "solo-dev/no-shell".into(),
                    matched: true,
                }],
                provenance: vec![],
                redactor_stack_hash: None,
                key_id: None,
                merkle_leaf: MerkleLeaf {
                    sequence: 1,
                    leaf_hash: Digest([3u8; 32]),
                    prev_hash: Digest([1u8; 32]),
                },
            },
        ),
        (
            "with-provenance-edges",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:02Z".into(),
                action: Action {
                    kind: "tool.http_fetch".into(),
                    target: "https://api.github.com/user".into(),
                    input_hash: Digest([4u8; 32]),
                },
                decision: Decision::Allowed,
                constitution_rules: vec![],
                provenance: vec![
                    ProvenanceEdge {
                        from: "user".into(),
                        to: "model".into(),
                        kind: "request".into(),
                    },
                    ProvenanceEdge {
                        from: "model".into(),
                        to: "tool:http_fetch".into(),
                        kind: "tool_call".into(),
                    },
                ],
                redactor_stack_hash: None,
                key_id: None,
                merkle_leaf: MerkleLeaf {
                    sequence: 2,
                    leaf_hash: Digest([5u8; 32]),
                    prev_hash: Digest([3u8; 32]),
                },
            },
        ),
        (
            "with-redactor-stack-hash",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:03Z".into(),
                action: Action {
                    kind: "$kernel/tool/executed".into(),
                    target: "tool=http_fetch status=ok".into(),
                    input_hash: Digest([0u8; 32]),
                },
                decision: Decision::Allowed,
                constitution_rules: vec![],
                provenance: vec![ProvenanceEdge {
                    from: "receipt:00".into(),
                    to: "redaction:default::github_pat:count=1".into(),
                    kind: "redaction_applied".into(),
                }],
                redactor_stack_hash: Some(Digest([0xAB; 32])),
                key_id: None,
                merkle_leaf: MerkleLeaf {
                    sequence: 3,
                    leaf_hash: Digest([6u8; 32]),
                    prev_hash: Digest([5u8; 32]),
                },
            },
        ),
        (
            "pending-approval",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:04Z".into(),
                action: Action {
                    kind: "git.push".into(),
                    target: "origin/main".into(),
                    input_hash: Digest([7u8; 32]),
                },
                decision: Decision::Pending,
                constitution_rules: vec![RuleRef {
                    id: "solo-dev/git-push-approval".into(),
                    matched: true,
                }],
                provenance: vec![],
                redactor_stack_hash: None,
                key_id: None,
                merkle_leaf: MerkleLeaf {
                    sequence: 4,
                    leaf_hash: Digest([8u8; 32]),
                    prev_hash: Digest([6u8; 32]),
                },
            },
        ),
        // Step 19a: a Allowed receipt where the kernel's signer
        // identifies itself with `key_id = "prod-2026"`. The new
        // field is sorted into JCS output between `issued_at` and
        // `merkle_leaf` (lexicographic).
        (
            "with-key-id-prod-2026",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:05Z".into(),
                action: Action {
                    kind: "http.fetch".into(),
                    target: "https://example.com/with-key-id".into(),
                    input_hash: Digest([9u8; 32]),
                },
                decision: Decision::Allowed,
                constitution_rules: vec![],
                provenance: vec![],
                redactor_stack_hash: None,
                key_id: Some("prod-2026".into()),
                merkle_leaf: MerkleLeaf {
                    sequence: 5,
                    leaf_hash: Digest([0x9a; 32]),
                    prev_hash: Digest([8u8; 32]),
                },
            },
        ),
        // Step 19a: a tool-execution receipt where the kernel
        // signed with `key_id = "hsm-3"`. Exercises the field
        // alongside `redactor_stack_hash` and a provenance edge.
        (
            "tool-execution-with-key-id-hsm-3",
            ReceiptBody {
                schema_version: RECEIPT_FORMAT_VERSION,
                issued_at: "2026-04-26T12:00:06Z".into(),
                action: Action {
                    kind: "$kernel/tool/executed".into(),
                    target: "tool=http_fetch status=ok".into(),
                    input_hash: Digest([0u8; 32]),
                },
                decision: Decision::Allowed,
                constitution_rules: vec![],
                provenance: vec![ProvenanceEdge {
                    from: "receipt:9a".into(),
                    to: "tool:http_fetch".into(),
                    kind: "tool_execution".into(),
                }],
                redactor_stack_hash: None,
                key_id: Some("hsm-3".into()),
                merkle_leaf: MerkleLeaf {
                    sequence: 6,
                    leaf_hash: Digest([0xb1; 32]),
                    prev_hash: Digest([0x9a; 32]),
                },
            },
        ),
    ]
}

/// Snapshot-tested expected outputs for [`vector_bodies`].
///
/// To regenerate after a deliberate canonicalizer change:
/// `cargo test -p uniclaw-receipt --test vectors -- --nocapture
///  print_vectors`, copy the printed `(canonical_hex, blake3_hex)`
/// pairs back into this list, and re-run.
fn expected_outputs() -> Vec<(&'static str, &'static str)> {
    vec![
        // [0] minimal-allowed
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030222c226b696e64223a22687474702e6665746368222c22746172676574223a2268747470733a2f2f6578616d706c652e636f6d2f227d2c22636f6e737469747574696f6e5f72756c6573223a5b5d2c226465636973696f6e223a22616c6c6f776564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30305a222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2230313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031222c22707265765f68617368223a2230303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030222c2273657175656e6365223a307d2c2270726f76656e616e6365223a5b5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "30136578ba36a251a0ef8e31fcfd0f4bcc619954e473861c9dee9d82be0bf00f",
        ),
        // [1] denied-with-rule
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032303230323032222c226b696e64223a227368656c6c2e65786563222c22746172676574223a22726d202d7266202f227d2c22636f6e737469747574696f6e5f72756c6573223a5b7b226964223a22736f6c6f2d6465762f6e6f2d7368656c6c222c226d617463686564223a747275657d5d2c226465636973696f6e223a2264656e696564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30315a222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2230333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033222c22707265765f68617368223a2230313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031303130313031222c2273657175656e6365223a317d2c2270726f76656e616e6365223a5b5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "7a82307aff255b2ef461b458cb2d2c9514841fc684ba3cc4de5b01eaa6828f40",
        ),
        // [2] with-provenance-edges
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230343034303430343034303430343034303430343034303430343034303430343034303430343034303430343034303430343034303430343034303430343034222c226b696e64223a22746f6f6c2e687474705f6665746368222c22746172676574223a2268747470733a2f2f6170692e6769746875622e636f6d2f75736572227d2c22636f6e737469747574696f6e5f72756c6573223a5b5d2c226465636973696f6e223a22616c6c6f776564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30325a222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2230353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035222c22707265765f68617368223a2230333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033303330333033222c2273657175656e6365223a327d2c2270726f76656e616e6365223a5b7b2266726f6d223a2275736572222c226b696e64223a2272657175657374222c22746f223a226d6f64656c227d2c7b2266726f6d223a226d6f64656c222c226b696e64223a22746f6f6c5f63616c6c222c22746f223a22746f6f6c3a687474705f6665746368227d5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "7103f76faa6eee24f35354ad81e40bc9bb6ada34866756b1040e403246636362",
        ),
        // [3] with-redactor-stack-hash
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030222c226b696e64223a22246b65726e656c2f746f6f6c2f6578656375746564222c22746172676574223a22746f6f6c3d687474705f6665746368207374617475733d6f6b227d2c22636f6e737469747574696f6e5f72756c6573223a5b5d2c226465636973696f6e223a22616c6c6f776564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30335a222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2230363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036222c22707265765f68617368223a2230353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035303530353035222c2273657175656e6365223a337d2c2270726f76656e616e6365223a5b7b2266726f6d223a22726563656970743a3030222c226b696e64223a22726564616374696f6e5f6170706c696564222c22746f223a22726564616374696f6e3a64656661756c743a3a6769746875625f7061743a636f756e743d31227d5d2c227265646163746f725f737461636b5f68617368223a2261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162222c22736368656d615f76657273696f6e223a327d",
            "4a09f06045db7268b652537529b47b7c817962d952ecda6f3dada0b2a05a292e",
        ),
        // [4] pending-approval
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230373037303730373037303730373037303730373037303730373037303730373037303730373037303730373037303730373037303730373037303730373037222c226b696e64223a226769742e70757368222c22746172676574223a226f726967696e2f6d61696e227d2c22636f6e737469747574696f6e5f72756c6573223a5b7b226964223a22736f6c6f2d6465762f6769742d707573682d617070726f76616c222c226d617463686564223a747275657d5d2c226465636973696f6e223a2270656e64696e67222c226973737565645f6174223a22323032362d30342d32365431323a30303a30345a222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2230383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038222c22707265765f68617368223a2230363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036303630363036222c2273657175656e6365223a347d2c2270726f76656e616e6365223a5b5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "e2f44f6ca11d5e864f2b53003aad88796fd3afffebefd796103016138d06a48e",
        ),
        // [5] with-key-id-prod-2026
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230393039303930393039303930393039303930393039303930393039303930393039303930393039303930393039303930393039303930393039303930393039222c226b696e64223a22687474702e6665746368222c22746172676574223a2268747470733a2f2f6578616d706c652e636f6d2f776974682d6b65792d6964227d2c22636f6e737469747574696f6e5f72756c6573223a5b5d2c226465636973696f6e223a22616c6c6f776564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30355a222c226b65795f6964223a2270726f642d32303236222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2239613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961222c22707265765f68617368223a2230383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038303830383038222c2273657175656e6365223a357d2c2270726f76656e616e6365223a5b5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "636bc6c174b51e0bbdf6771e21b4ce2aa355822c9127b80a27ac7991e2307067",
        ),
        // [6] tool-execution-with-key-id-hsm-3
        (
            "7b22616374696f6e223a7b22696e7075745f68617368223a2230303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030222c226b696e64223a22246b65726e656c2f746f6f6c2f6578656375746564222c22746172676574223a22746f6f6c3d687474705f6665746368207374617475733d6f6b227d2c22636f6e737469747574696f6e5f72756c6573223a5b5d2c226465636973696f6e223a22616c6c6f776564222c226973737565645f6174223a22323032362d30342d32365431323a30303a30365a222c226b65795f6964223a2268736d2d33222c226d65726b6c655f6c656166223a7b226c6561665f68617368223a2262316231623162316231623162316231623162316231623162316231623162316231623162316231623162316231623162316231623162316231623162316231222c22707265765f68617368223a2239613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961396139613961222c2273657175656e6365223a367d2c2270726f76656e616e6365223a5b7b2266726f6d223a22726563656970743a3961222c226b696e64223a22746f6f6c5f657865637574696f6e222c22746f223a22746f6f6c3a687474705f6665746368227d5d2c227265646163746f725f737461636b5f68617368223a6e756c6c2c22736368656d615f76657273696f6e223a327d",
            "d5d12da483fda2d001a60a9ae599a3176a9e34639947a41235589dbe021a3eca",
        ),
    ]
}

/// Print the canonical-bytes and BLAKE3 for every vector. Used to
/// (re)generate [`expected_outputs`]. Doesn't assert; running this
/// is how you produce the table.
#[test]
#[ignore = "regenerator: produces test-vector pairs to paste back"]
fn print_vectors() {
    for (i, (name, body)) in vector_bodies().iter().enumerate() {
        let canonical = uniclaw_receipt::canonical::to_vec(body).unwrap();
        let hash = blake3::hash(&canonical);
        println!(
            "// [{i}] {name}\n(\"{}\", \"{}\"),",
            hex_encode(&canonical),
            hex_encode(hash.as_bytes()),
        );
    }
}

/// The actual snapshot test. Compares each vector's canonical
/// bytes + BLAKE3 against the pinned values in
/// [`expected_outputs`]. Skipped when `expected_outputs` is still
/// the placeholder ("`REGEN_ME`") — rerun `print_vectors` and
/// paste in real values.
#[test]
fn vectors_match_expected_canonical_and_hash() {
    let bodies = vector_bodies();
    let expected = expected_outputs();
    assert_eq!(
        bodies.len(),
        expected.len(),
        "vector list lengths must match"
    );

    for (i, ((name, body), (exp_canonical_hex, exp_hash_hex))) in
        bodies.iter().zip(expected.iter()).enumerate()
    {
        if *exp_canonical_hex == "REGEN_ME" {
            eprintln!("[{i}] {name}: SKIP (placeholder; run print_vectors and paste back)");
            continue;
        }
        let canonical = uniclaw_receipt::canonical::to_vec(body).unwrap();
        let canonical_hex = hex_encode(&canonical);
        let hash = blake3::hash(&canonical);
        let hash_hex = hex_encode(hash.as_bytes());

        assert_eq!(
            canonical_hex, *exp_canonical_hex,
            "[{i}] {name}: canonical bytes diverged",
        );
        assert_eq!(hash_hex, *exp_hash_hex, "[{i}] {name}: hash diverged");
    }
}

/// Auto-generate (or refresh) the JSON fixture file under
/// `tests/vectors/canonical-v2.json` from the current bodies +
/// the canonicalizer's output. The fixture is what cross-language
/// verifiers (TypeScript browser verifier, future Go/Python ports)
/// load to confirm they produce identical bytes.
///
/// `#[ignore]` so it doesn't run in the normal test sweep — the
/// fixture is committed and changes only when canonicalization
/// changes, in which case the operator runs this manually.
#[test]
#[ignore = "regenerator: writes tests/vectors/canonical-v2.json"]
fn dump_canonical_vectors_to_file() {
    use std::fmt::Write as FmtWrite;
    use std::io::Write as IoWrite;
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("vectors")
        .join("canonical-v2.json");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();

    let mut out = String::new();
    out.push_str("{\n  \"format\": \"uniclaw-canonical-v2\",\n  \"vectors\": [\n");
    for (i, (name, body)) in vector_bodies().iter().enumerate() {
        let canonical = uniclaw_receipt::canonical::to_vec(body).unwrap();
        let hash = blake3::hash(&canonical);
        let body_pretty = serde_json::to_string(body).unwrap();
        if i > 0 {
            out.push_str(",\n");
        }
        let _ = write!(
            out,
            "    {{\n      \"name\": \"{name}\",\n      \"body\": {body_pretty},\n      \"canonical_hex\": \"{}\",\n      \"blake3_hex\": \"{}\"\n    }}",
            hex_encode(&canonical),
            hex_encode(hash.as_bytes()),
        );
    }
    out.push_str("\n  ]\n}\n");

    let mut f = std::fs::File::create(&path).unwrap();
    f.write_all(out.as_bytes()).unwrap();
    println!(
        "wrote {} ({} vectors)",
        path.display(),
        vector_bodies().len()
    );
}

fn hex_encode(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}
